<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Whooz_whooApp-59668b39-04bd-4b60-a198-d3aa2a61337a</UserSecretsId>
    <RootNamespace>Whooz_whooApp</RootNamespace>
    <AssemblyName>`$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Whooz_whooApp.Client\Whooz_whooApp.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.*" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="3.*" />
  </ItemGroup>

</Project>