<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Whooz_whoo.App-dbb3c3f7-3858-4d26-a9bc-75b7c1f7e04e</UserSecretsId>
    <RootNamespace>Whooz_whoo.App</RootNamespace>
    <AssemblyName>`$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.*" />
    <PackageReference Include="MudBlazor" Version="8.*" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="3.*" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="API\Endpoints\" />
    <Folder Include="API\Middleware\" />
  </ItemGroup>

</Project>